### ISSUE TITLE
楼主好，是否可以加微信一起交流。

### ISSUE THREAD

**Issue by Snailovet** [wstclzy2010/PureNewSocial#1]
我也是学习iOS插件开发一年。
这是我的源 repo.snailovet.com
感觉国内从事逆向插件开发的人很少，方便留联一起交流学习嘛。

**Comment by wstclzy2010** [comment]
> 我也是学习iOS插件开发一年。
> 这是我的源 repo.snailovet.com
> 感觉国内从事逆向插件开发的人很少，方便留联一起交流学习嘛。

因为不方便直接写在这里，你在网页打开https://wstclzy2010.github.io/repo/ 
可以看到我的微博或者威锋，用它们私信我

**Comment by Snailovet** [comment]
你的源打开显示404啦

**Comment by wstclzy2010** [comment]
> 你的源打开显示404啦

没有啊，你复制再打开吧，别直接点连接

**Comment by Snailovet** [comment]
嗯嗯 今天能打开啦 微博留言啦
